---
title: Getting Started
subtitle: Installation and Setup
metadata-files:
  - ../_metadata.yml
order: 1
---

:::{.callout-note}
The instructions on this page only need to be carried out once. If you have already installed the required dependencies and created a virtual environment, skip ahead to [Using the Model](usage.qmd).
:::

Download and install Python [3.10](https://www.python.org/downloads/release/python-31011/) (recommended) or 3.9, if needed. If this is your first installation of Python on your workstation, check the "Add Python to PATH" box during the installation.

## Basic Users

These instructions assume no working knowledge of command line interface or GitHub.

Download the [FATES-BLH-ScaleAgeing repository](https://github.com/SEFSC/FATES-BLH-ScaleAgeing) from GitHUb: click the green "<> Code" button and select "Download ZIP". Extract to your desired local location.

To use the Segment Anything Model (SAM) for image processing, [download this model](#download-segmentation-model) as well. Otherwise, skip this step and use simple binary segmentation.

## Advanced Users

Much of the following is carried out using command line. In the instructions below, "command line terminal" or "terminal" refer to any command line application for the given operating system. For Windows, this is commonly Command Prompt or Windows Powershell. These use DOS commands. For UNIX users, Git Bash is a good alternative; it is included in [Git for Windows](#git) and allows UNIX commands to be used instead of DOS.

#### Git Installation

Download and install [git](https://git-scm.com/downloads). This does not need administrative privileges to install at the user level. Open the newly-installed Git Bash application and verify everything is working by typing

```bash
git --version
```

This should display the version of git installed on the system.

:::{.callout-note}
This should already be installed for all users on the Advanced Technology GPU machine.
:::

#### Clone the Repository

The model code and most of its dependencies are [available on GitHub]({{< meta website.repo-url >}}). To retrieve it, clone the `{{< meta repo.prod-branch >}}` branch of this repo, which is currently functioning as the production version of the model:

1. Open Git Bash and change directories (`cd`) to wherever you want the code to reside. For example,

   ```bash
   cd Documents/ageing
   ```

   :::{.callout-important}
   Make sure the directory exists before trying to navigate into it. You cannot move into a non-existent folder.
   :::

2. Clone the repository into the desired directory

   ```bash
   git clone -b {{< meta repo.prod-branch >}} {{< meta website.repo-url >}} .
   ```

   if you want all of the repo contents in the current directory, or 
   
   ```bash
   git clone -b {{< meta repo.prod-branch >}} {{< meta website.repo-url >}}
   ```

   if you want the repo contents to be downloaded into a new subdirectory called `{{< meta repo.name >}}`. This is just personal preference. (Note the difference between the two commands is the dot `.` at the end.)

### Download Segmentation Model

This model has the option of using a [Segment Anything Model](https://arxiv.org/abs/2408.00714) (SAM) to find the scale within each image. To use this method, one must [download a model checkpoint](https://github.com/facebookresearch/segment-anything?tab=readme-ov-file#model-checkpoints). The [ViT-B model](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth) is recommended. For convenience, consider saving this file in the same directory as model script, for example `~/{{< meta repo.name >}}/scripts/weights`.

::: {.callout-important}
You only need to download this if you intend to use Segment Anything Model method to image preprocessing. See [Using the Model](usage.qmd#configuration-file) for more information. 
:::

### Virtual Environment

A Python virtual environment will automatically be created and configured the first time you [launch the model or process images](usage.qmd). The utility will automatically:

1. Check the system for a compatible Python installation. If none is found, the user will be prompted to [install the appropriate version](#getting-started) and directed to the official Python distribution site.
2. Look for a project-specific Python virtual environment (called `.venv`) in the project parent folder. If one is found, it will be activated. Otherwise, one will be created and activated and the required Python packages will be installed in it from the provided `requirements.txt` file. This may take several minutes to complete but only needs to happen once.

::: {.callout-tip title="Windows path limits"}

If package installation fails, it may be due to [Windows path length limitations](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry). The most common culprit of this is PyTorch, which contains thousands of files within nested directories. Try relocating the downloaded or cloned project folder to a higher level directory on your machine. For example, if your project is currently in `C:\Users\user.name\Documents\models\menhaden\ageing\FATES-BLH-ScaleAgeing`, a path that itself contains more than 70 characters out of the allotted 250, consider moving it -- and renaming the project directory to, for example, `C:\Users\user.name\Documents\ageing`. Alternatively, the 250-character limit can be disabled with a Windows registry setting, but this will require administrator privileges.

:::

If an installation fails or you want to reinstall something, the easiest way to do so is to delete the `.venv` directory and relaunch the model. 