# ------------------------------------------------------------------------------
#                     Paths, file names, and other settings
# ------------------------------------------------------------------------------
# Accepts forward slash (/), back slash (\), or double back slash (\\) dividers.
# Best to wrap in single quotations ('...'). For example:
# 'G:/Shared drives/NMFS SEFSC FATES Advanced Technology'

# Path to raw images
raw_image_path: 'G:/Shared drives/NMFS SEFSC FATES Advanced Technology/BIOLOGY_LIFE_HISTORY_DATA/2020_Plant_10/images'

# Path to save processed images
processed_image_path: 'G:/Shared drives/NMFS SEFSC FATES Advanced Technology/BIOLOGY_LIFE_HISTORY_DATA/2020_Plant_10/cropped'

# Input image type
input_type: '.tif'

# Path and name of metadata CSV file for age inference with multimodal model.
# (Ignored if using the 'image only' model.)
metadata_csv_file: 'G:/Shared drives/NMFS SEFSC FATES Advanced Technology/BIOLOGY_LIFE_HISTORY_DATA/2020_Plant_10/metadata/metadata.csv'

# Relevant database field names. Wrap in quotations to support spaces.
fish_id_colname: 'Scaleno'
fish_length_colname: 'Fork Length Mm'
fish_weight_colname: 'Weight G'
collection_date_colname: 'Month'

# Path and name of file to save age predictions
output_csv_file: 'G:/Shared drives/NMFS SEFSC FATES Advanced Technology/BIOLOGY_LIFE_HISTORY_DATA/2020_Plant_10/model_predictions/predictions.csv'

# If cropping/padding fails, due to, e.g., variations in image coloring, such as
# foreground/background constrast, try tweaking `binary_threshold` first
# (default 100), followed by `bottom_pad` and `pad`, as needed (defaults 0.35
# and 0.05, respectively.) Use trial and error until the processed images turn
# out as desired.

# -----Binary Threshold Segmentation-----
# Binary threshold pixel value for differentiation between foreground (scale)
# and background. Tweak this as needed to ensure the scales are properly located
# within the images. Default: 100.
# binary_threshold: 100 #Remove comment (#) from the start of this line to edit

# -----Cropping parameters-----
# Padding for top and sides of cropped image. Defined as a fraction of the
# original cropped image size. Bottom padding is controlled by bottom_pad.
# Adjust as needed to ensure the there is a margin around the top and sides of
# the extracted scale. Setting a value low may because the scale to 'bleed' when
# the image is resized for input to the model. Setting a value too high may
# include too much background and make the scale too small in the image.
# Default: 0.05
# pad: 0.05 #Remove comment (#) from the start of this line to edit

# Padding for bottom of cropped image. This is defined separately since for
# scale images, the bottom is usually visually distinct from the body and may be
# missed in the segmentation. Adjust as needed to ensure the there is a margin
# at the bottom of the extracted scale. Setting a value low may because the
# scale to 'bleed' when the image is resized for input to the model. Setting a
# value too high may include too much background and make the scale too small in
# the image. Default: 0.35
# bottom_pad: 0.35 #Remove comment (#) from the start of this line to edit
